version: '3.3'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_volume:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090


  mysql:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: ./server
    restart: always
    ports:
      - 80:80
    depends_on:
      - mysql
    environment:
      DB_PASS: pass
      DB_USER: root
      DB_HOST: mysql
      DB_NAME: db
      DB_MAX_RETRIES: 5
    volumes:
      - ./db_connection:/app/db_connection

  administrator:
    build: ./administrator
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    environment:
      DB_PASS: pass
      DB_USER: root
      DB_HOST: mysql
      DB_NAME: db
      DB_MAX_RETRIES: 5
    volumes:
      - ./db_connection:/app/db_connection

  filter:
    build: ./filter
    restart: always
    depends_on:
      - mysql
    environment:
      DB_PASS: pass
      DB_USER: root
      DB_HOST: mysql
      DB_NAME: db
      DB_MAX_RETRIES: 5
      FILTER_RERUN_TIMER_MINUTES: 1
    volumes:
      - ./db_connection:/app/db_connection

volumes:
  prometheus_volume: {}