version: '3.3'

services:
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db

  server:
    build: ./server
    restart: always
    ports:
      - 80:80
    depends_on:
      - mysql
    environment:
      DB_PASS: pass
      DB_USER: root
      DB_HOST: mysql
      DB_NAME: db
      DB_MAX_RETRIES: 5

  administrator:
    build: ./administrator
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    environment:
      DB_PASS: pass
      DB_USER: root
      DB_HOST: mysql
      DB_NAME: db
      DB_MAX_RETRIES: 5

volumes:
  mysql-volume: {}