version: '3.3'

services:
  mysql:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: ./server
    restart: always
    ports:
      - 80:80
    depends_on:
      - mysql
    environment:
      DB_PASS: pass
      DB_USER: root
      DB_HOST: mysql
      DB_NAME: db
      DB_MAX_RETRIES: 5

  administrator:
    build: ./administrator
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    environment:
      DB_PASS: pass
      DB_USER: root
      DB_HOST: mysql
      DB_NAME: db
      DB_MAX_RETRIES: 5

  filter:
    build: ./filter
    restart: always
    depends_on:
      - mysql
    environment:
      DB_PASS: pass
      DB_USER: root
      DB_HOST: mysql
      DB_NAME: db
      DB_MAX_RETRIES: 5
      FILTER_RERUN_TIMER_HOURS: 24

volumes:
  mysql-volume: {}